# Site settings
title: Node Only
email: i5ting@126.com
description: > # this means to ignore newlines until "baseurl:"
  Write an awesome practice for Nodejs here.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://nodeonly.com" # the base hostname & protocol for your site
twitter_username: nodeonly
github_username:  nodeonly

# Build settings
markdown: kramdown
comments :
provider : duoshuo
duoshuo : 
  short_name : nodeonly
